trigger:
- main

pool:
  name: may-pool

variables:
  nodeVersion: '18.x'

stages:

- stage: Build
  displayName: Build Application

  jobs:
  - job: BuildJob
    displayName: Build React App

    steps:

    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: Install NodeJS

    - script: |
        npm install
      displayName: Install Dependencies

    - script: |
        npm run build
      displayName: Build React App

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)\build'
        ArtifactName: 'react-build'
      displayName: Publish Build Artifact