trigger:
- main

pool:
  name: may-pool

variables:
  nodeVersion: '18.x'

stages:

- stage: Build
  displayName: Build Application

  jobs:
  - job: BuildJob

    steps:

    - checkout: self
      path: Chat-application

    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: Install NodeJS

    - script: |
        npm install
      workingDirectory: '$(Pipeline.Workspace)\Chat-application\app\chat_application'
      displayName: Install Dependencies

    - script: |
        npm run build
      workingDirectory: '$(Pipeline.Workspace)\Chat-application\app\chat_application'
      displayName: Build React App

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Pipeline.Workspace)\Chat-application\app\chat_application\build'
        ArtifactName: 'react-build'
      displayName: Publish Build Artifact